/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KeyboardShortcut {
    'commandControl': boolean;
    'key': string;
    'shift': boolean;
  }
  interface KeyboardShortcutAttributes extends StencilHTMLAttributes {
    'commandControl'?: boolean;
    'key'?: string;
    'shift'?: boolean;
  }

  interface KeyboardShortcutsOverlay {
    'dialogTitle': string;
  }
  interface KeyboardShortcutsOverlayAttributes extends StencilHTMLAttributes {
    'dialogTitle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KeyboardShortcut': Components.KeyboardShortcut;
    'KeyboardShortcutsOverlay': Components.KeyboardShortcutsOverlay;
  }

  interface StencilIntrinsicElements {
    'keyboard-shortcut': Components.KeyboardShortcutAttributes;
    'keyboard-shortcuts-overlay': Components.KeyboardShortcutsOverlayAttributes;
  }


  interface HTMLKeyboardShortcutElement extends Components.KeyboardShortcut, HTMLStencilElement {}
  var HTMLKeyboardShortcutElement: {
    prototype: HTMLKeyboardShortcutElement;
    new (): HTMLKeyboardShortcutElement;
  };

  interface HTMLKeyboardShortcutsOverlayElement extends Components.KeyboardShortcutsOverlay, HTMLStencilElement {}
  var HTMLKeyboardShortcutsOverlayElement: {
    prototype: HTMLKeyboardShortcutsOverlayElement;
    new (): HTMLKeyboardShortcutsOverlayElement;
  };

  interface HTMLElementTagNameMap {
    'keyboard-shortcut': HTMLKeyboardShortcutElement
    'keyboard-shortcuts-overlay': HTMLKeyboardShortcutsOverlayElement
  }

  interface ElementTagNameMap {
    'keyboard-shortcut': HTMLKeyboardShortcutElement;
    'keyboard-shortcuts-overlay': HTMLKeyboardShortcutsOverlayElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
